trigger:
  # think about using batching to cut down on overlapping runs
  #batch: true
  branches:
    include:
    - main
  paths:
    include:
    # common
    - 'XamarinPipelineDemo'
    - 'XamarinPipelineDemo.NUnit'
    - 'XamarinPipelineDemo.UITest'
    - 'XamarinPipelineDemo.sln'
    # platform
    - 'XamarinPipelineDemo.Android'

pool:
  vmImage: 'macos-latest'

variables:
  - group: android_demo_var_group

  - name: appName
    value: 'XamarinPipelineDemo'

  - name: solution
    value: '$(Build.SourcesDirectory)/$(appName).sln'

  - name: buildConfiguration
    value: 'Release'

  - name: outputDir
    value: '$(Build.BinariesDirectory)/$(buildConfiguration)'

  - name: pipelineBuildNumber
    value: $[counter(variables['Build.DefinitionName'], 1)]

  - name: finalApkCommonPart
    value: '$(Build.ArtifactStagingDirectory)/$(appName)_$(Build.BuildNumber)_$(pipelineBuildNumber)'

  - name: finalApkPathUnsigned
    value: '$(finalApkCommonPart)_Unsigned.apk'

  - name: finalApkPathSigned
    value: '$(finalApkCommonPart)_Signed.apk'

  - name: androidDir
    value: '$(Build.SourcesDirectory)/$(appName).Android'

  - name: androidPipelineDir
    value: '$(androidDir)/AzureDevOps'

  - name: nugetPackageDir
    value: '$(System.DefaultWorkingDirectory)/packages'

  - name: uiTestDir
    value: '$(Build.SourcesDirectory)/$(appName).UITest'

  - name: uiTestAssemblyDir
    value: '$(uiTestDir)/bin/$(buildConfiguration)'

  - name: uiTestResultPath
    value: '$(Build.ArtifactStagingDirectory)/uitest_result.xml'

  - name: uiTestLogPath
    value: '$(Build.ArtifactStagingDirectory)/uitest.log'

  - name: adb
    value: '$ANDROID_HOME/platform-tools/adb'

  - name: emulator
    value: '$ANDROID_HOME/emulator/emulator'

  - name: appCenterOutputDir
    value: '$(Build.ArtifactStagingDirectory)/AppCenterTest'

  - name: appCenterTestResultsDir
    value: '$(appCenterOutputDir)/TestResults'

  - name: appCenterOrgName
    value: 'JacobEgnerDemos'

  - name: wantAppCenterUiTests
    value: true

  - name: wantEmulatorUiTests
    value: true

  # set this to false when things are working and you don't need to debug
  # pipeline problems
  - name: System.Debug
    value: true

################################################################################
steps:

################################################################################
# build app and make APK

# doing a new Xamarin Android app pipeline gets you this task
- task: NuGetToolInstaller@1

# doing a new Xamarin Android app pipeline gets you a simpler form of this task
- task: NuGetCommand@2
  displayName: 'nuget-restore solution'
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  displayName: 'Set build-based Android app version'
  inputs:
    filePath: '$(androidPipelineDir)/AndroidSetVersion.ps1'
    arguments: >
      -manifestPath '$(androidDir)/Properties/AndroidManifest.xml'
      -versionCodeBase 0
      -versionCodeOffset $(pipelineBuildNumber)
      -versionName '$(Build.BuildNumber)'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDir: '$(outputDir)'
    configuration: '$(buildConfiguration)'

- pwsh: Get-ChildItem -Recurse "$(outputDir)/*.apk" | ForEach-Object { Copy-Item $_ -Destination "$(finalApkPathUnsigned)" }
  displayName: 'copy and rename unsigned apk'

# REMINDER: You need to upload
# XamarinPipelineDemo.Android/AzureDevops/example.keystore as a secure file and
# make android_demo_var_group variable group with the following variables...
#   androidKeystoreSecureFileName: example.keystore
#   androidKeyAlias: androiddebugkey
#   androidKeystorePassword: android
#   androidKeyPassword: android
- task: AndroidSigning@3
  displayName: 'sign APK with example keystore'
  inputs:
    apkFiles: '$(outputDir)/*.apk'
    apksignerKeystoreFile: '$(androidKeystoreSecureFileName)'
    apksignerKeystoreAlias: '$(androidKeyAlias)'
    apksignerKeystorePassword: '$(androidKeystorePassword)'
    apksignerArguments: '--verbose --out $(finalApkPathSigned)'

- task: PublishBuildArtifacts@1
  displayName: 'publish APK artifacts'
  inputs:
   artifactName: 'apks'

################################################################################
# unit tests

# our unit test project is .net core, so "dotnet test" works on it
- task: DotNetCoreCLI@2
  displayName: 'unit tests'
  inputs:
    command: 'test'
    projects: '**/*NUnit*.csproj'
    configuration: '$(buildConfiguration)'

################################################################################
# UI tests, preparatory steps common to App Center and emulator

- task: MSBuild@1
  displayName: 'build ui tests'
  condition: >
    and(
      succeeded(),
      or(
        eq(variables.wantAppCenterUiTests, true),
        eq(variables.wantEmulatorUiTests, true)
      )
    )
  inputs:
    solution: '**/*UITest*.csproj'
    configuration: '$(buildConfiguration)'

################################################################################
# emulator UI tests
# lots of inspiration from https://medium.com/genetec-tech/android-ui-testing-in-azure-devops-81bbe7cea9fd
# older sources of inspiration from...
# https://github.com/janpio/azure-pipelines-android_emulator
# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops#test-on-the-android-emulator

- bash: |
    set -o xtrace
    $ANDROID_HOME/tools/bin/sdkmanager --list
    echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-30;google_apis;x86'
  displayName: 'install Android image'
  condition: and(succeeded(), eq(variables.wantEmulatorUiTests, true))

- bash: |
    set -o xtrace
    $(emulator) -list-avds
    echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n uitest_android_emulator -k 'system-images;android-30;google_apis;x86' --force
    $(emulator) -list-avds
  displayName: 'create AVD'
  condition: and(succeeded(), eq(variables.wantEmulatorUiTests, true))

- bash: |
    set -o xtrace
    $(adb) devices
    nohup $(emulator) -avd uitest_android_emulator -no-snapshot -no-boot-anim -gpu auto -qemu > /dev/null 2>&1 &
  displayName: 'start Android emulator'
  condition: and(succeededOrFailed(), eq(variables.wantEmulatorUiTests, true))

- bash: |
    set -o xtrace
    $(adb) wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
    $(adb) devices
  displayName: 'wait for Android emulator'
  condition: and(succeeded(), eq(variables.wantEmulatorUiTests, true))
  timeoutInMinutes: 5

# have to run nunit3-console directly; as of 2020-12-17, even though "dotnet
# run" works with Mono to run .net framework projects, "dotnet test" does not
# work the same project; see open issue https://github.com/mono/mono/issues/6984
- pwsh: |
    Set-PSDebug -Trace 1
    $env:UITEST_APK_PATH = "$(finalApkPathSigned)"
    $testAssemblies = Get-Item "$(uiTestDir)/bin/$(buildConfiguration)/$(appName).UITest*.dll"
    nunit3-console $testAssemblies --output="$(uiTestLogPath)" --result="$(uiTestResultPath)"
  displayName: 'run android emulator ui tests'
  condition: and(succeeded(), eq(variables.wantEmulatorUiTests, true))
  continueOnError: true
  timeoutInMinutes: 120

- task: PublishBuildArtifacts@1
  displayName: 'publish emulator ui test log artifact'
  condition: and(succeededOrFailed(), eq(variables.wantEmulatorUiTests, true))
  continueOnError: true
  inputs:
   artifactName: 'Android emulator UI test log'
   pathToPublish: '$(uiTestLogPath)'

- task: PublishTestResults@2
  condition: and(succeededOrFailed(), eq(variables.wantEmulatorUiTests, true))
  inputs:
    testRunTitle: 'Android Emulator UI Test Run'
    testResultsFormat: 'NUnit'
    testResultsFiles: '$(uiTestResultPath)'
    # Android tests may randomly fail because of the System UI not responding (if you're using Prism);
    # see https://github.com/PrismLibrary/Prism/issues/2099 ;
    # tests may also fail due to pool agent problems;
    # using the following line still makes builds have warning status when UI tests fail
    failTaskOnFailedTests: false

################################################################################
# AppCenter UI tests

# default nodejs version (v12) is not compatible with stuff used in AppCenterTest task
# https://github.com/microsoft/appcenter-cli/issues/696#issuecomment-553218361
- task: UseNode@1
  displayName: 'Use Node 10.15.1'
  condition: and(succeeded(), eq(variables.wantAppCenterUiTests, true))
  inputs:
    version: 10.15.1

- task: AppCenterTest@1
  condition: and(succeeded(), eq(variables.wantAppCenterUiTests, true))
  continueOnError: true
  inputs:
    appFile: '$(finalApkPathSigned)'
    appSlug: '$(appCenterOrgName)/$(appName)' # orgname or username, then '/', then app name
    devices: '$(appCenterOrgName)/demo_device_set' # uses same orgname or username, then '/', then device set name
    frameworkOption: 'uitest'
    runOptions: --test-output-dir "$(appCenterOutputDir)" # only needed if publishing test results in Azure DevOps
    serverEndpoint: 'AppCenterConnectionUserBasedFullAccess' # make a App Center user API token, then add service connection in Azure DevOps
    uiTestBuildDirectory: '$(uiTestAssemblyDir)' # directory that contains the uitest assemblies, not the build directory
    uiTestToolsDirectory: '$(uiTestAssemblyDir)' # build process puts test-cloud.exe in assembly dir

- pwsh: Expand-Archive "$(appCenterOutputDir)/nunit_xml_zip.zip" -DestinationPath "$(appCenterTestResultsDir)"
  displayName: 'unzip App Center test results zip'
  condition: and(succeededOrFailed(), eq(variables.wantAppCenterUiTests, true))
  continueOnError: true

- task: PublishTestResults@2
  displayName: 'simple publish App Center UI test results'
  condition: and(succeededOrFailed(), eq(variables.wantAppCenterUiTests, true))
  inputs:
    testRunTitle: 'Android App Center UI Test Run'
    testResultsFormat: 'NUnit'
    testResultsFiles: '$(appCenterTestResultsDir)/*.xml'

- pwsh: |
    Get-ChildItem .\artifacts\xmls\ | ForEach-Object { Write-Output `
        ( "##vso[results.publish " `
        + "runTitle=Android App Center UI Test Run $($_.BaseName);" `
        + "resultFiles=$($_.FullName);" `
        + "type=NUnit;" `
        + "mergeResults=false;" `
        + "publishRunAttachments=true;" `
        + "failTaskOnFailedTests=false;" `
        + "testRunSystem=VSTS - PTR; `
        + "]" `
        )}
  displayName: 'complicated publish App Center UI test results with device name'
  condition: and(succeededOrFailed(), eq(variables.wantAppCenterUiTests, true))

